---
- name: Start Nginx
  service:
    name={{ nginx_service_name }}
    state=started
    enabled=yes

- name: Restart Nginx
  service:
    name={{ nginx_service_name }}
    state=restarted
    enabled=yes

- name: Start PHP-FPM
  service:
    name={{ php_fpm_service_name }}
    state=started
    enabled=yes

- name: Start PHP7-FPM
  service:
    name={{ php7_fpm_service_name }}
    state=started
    enabled=yes

- name: Restart PHP-FPM
  service:
    name={{ php_fpm_service_name }}
    state=restarted
    enabled=yes

- name: Restart PHP7-FPM
  service:
    name={{ php7_fpm_service_name }}
    state=restarted
    enabled=yes

- name: Restart MySQL
  service:
    name={{ mysql_service_name }}
    state=restarted
    enabled=yes

- name: Restart Freeradius
  service:
    name={{ freeradius_service_name }}
    state=restarted
    enabled=yes

- name: Restart Nodejs Socketio
  service:
    name={{ nodejs_socketio_service_name }}
    state=restarted
    enabled=yes

- name: Restart PPTPD
  service:
    name={{ pptpd_service_name }}
    state=restarted
    enabled=yes

- name: Start Coovachilli
  service:
    name={{ coovachilli_service_name }}
    state=started
    enabled=yes

- name: Restart Coovachilli
  service:
    name={{ coovachilli_service_name }}
    state=restarted
    enabled=yes
