---
# Apache (Ubuntu 14+)
apache_pkg_name: apache2

# RadiusDesk Packages (Ubuntu 14+)
rd_pkgs:
 - language-pack-en-base
 - language-pack-af
 - language-pack-fa
 - mysql-server
 - mysql-client
 - python-mysqldb
 - subversion
 - git
 - unzip
 - tar

# RadiusDesk PHP5 Packages (Ubuntu 14+)
rd_php5_pkgs:
 - php5-fpm
 - php5-mysql
 - php5-xcache
 - php5-cli
 - php5-gd
 - php5-curl
 - php5-intl
 - php5-xml
 - php5-mbstring

# RadiusDesk PHP7 Packages (Ubuntu 14+)
rd_php7_pkgs:
 - php7.0-fpm
 - php7.0-mysql
 - php7.0-cli
 - php7.0-gd
 - php7.0-curl
 - php7.0-intl
 - php7.0-xml
 - php7.0-mbstring

# Nginx (Ubuntu 14+)
nginx_pkg_name: nginx
nginx_service_name: nginx
nginx_webroot: "/usr/share/nginx/html"
nginx_config: "/etc/nginx/nginx.conf"
nginx_default_config: "/etc/nginx/sites-enabled/default"
nginx_worker_processes: 4
nginx_user: www-data

# General PHP (Ubuntu 14+)
php_session_save_path: "/tmp"
php_timezone: "Africa/Lagos"

# PHP5-FPM (Ubuntu 14+)
php_fpm_service_name: php5-fpm
php_fpm_config: "/etc/php5/fpm/pool.d/www.conf"
php_fpm_socket: "/var/run/php5-fpm.sock"
php_config_file: "/etc/php5/cli/php.ini"


# PHP7-FPM (Ubuntu 14+)
php7_fpm_service_name: php7.0-fpm
php7_fpm_config: "/etc/php/7.0/fpm/pool.d/www.conf"
php7_fpm_socket: "/var/run/php/php7.0-fpm.sock"
php7_config_file: "/etc/php/7.0/cli/php.ini"

# Web server (Ubuntu 14+)
web_user: www-data
web_group: www-data

# Temporary Download Directory
temp_src_dir: "/tmp/rd_sources"

# Radiusdesk Sources Repo Paths (Ubuntu 14+)
cakephp_git_repo: "https://github.com/cakephp/cakephp.git"
rd_svn_repo: "https://svn.code.sf.net/p/radiusdesk/code/trunk/rd"
rd_cake_svn_repo: "https://svn.code.sf.net/p/radiusdesk/code/trunk/rd_cake"
rd_cake3_svn_repo: "https://svn.code.sf.net/p/radiusdesk/code/trunk/cake3"
rd_login_svn_repo: "https://svn.code.sf.net/p/radiusdesk/code/trunk/rd_login"
extjs_src_url: "https://sourceforge.net/p/radiusdesk/code/HEAD/tree/extjs/ext-6-sencha_cmd.tar.gz?format=raw"
extjs_62_src_url: "http://svn.code.sf.net/p/radiusdesk/code/extjs/ext-6-2-sencha_cmd.tar.gz"
extjs_src_md5_sum: "e829741694be90a27d7f0c6a24dbfc8b"
extjs_62_src_md5_sum: "012c607cfb30b0e83da385d02d69c99c"
rd_svn_revision: 2085

# Freeradius Packages (Ubuntu 14+)
freeradius_pkgs:
 - "freeradius=3.0.11-ppa3*"
 - "freeradius-utils=3.0.11-ppa3*"
 - "freeradius-mysql=3.0.11-ppa3*"
 - "freeradius-ldap=3.0.11-ppa3*"
 - "freeradius-krb5=3.0.11-ppa3*"
 - "freeradius-common=3.0.11-ppa3*"
 - libnet-telnet-perl

# Freeradius (Ubuntu 14+)
freeradius_conf_dir: "/etc/freeradius"
freeradius_prefix_path: "/usr"
freeradius_sbin_dir: "/usr/sbin"
freeradius_bin_dir: "/usr/bin"
freeradius_shared_dir: "/usr/share/freeradius"
freeradius_service_name: freeradius
freeradius_user: freerad
freeradius_group: freerad
freeradius_log_dir: "/var/log/freeradius"
freeradius_radclient: "/usr/bin/radclient"
freeradius_secret: "testing123"
allow_vulnerable_openssl: yes

# Radiusdesk Database (Ubuntu 14+)
rd_db_user: rd
rd_db_password: rd
rd_db_name: rd

# MySQL (Ubuntu 14+)
mysql_old_root_password: ""
mysql_root_password: root
mysql_service_name: mysql
mysql_db_hosts:
 - 127.0.0.1
 - localhost
mysql_my_cnf: "~/.my.cnf"

# Nodejs Packages (Ubuntu 14+)
nodejs_pkgs:
 - python-software-properties
 - software-properties-common
 - g++
 - make
 - nodejs

# Nodejs Modules (Ubuntu 14+)
nodejs_npm_modules:
 - tail
 - connect
 - mysql
 - forever

nodejs_socketio_service_name: "nodejs-socket-io"
nodejs_socketio_app_path: "/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript:/usr/local/lib/node_modules/"

# PPTPD
enable_pptpd_support: yes
pptpd_service_name: pptpd
pptpd_local_ip_network: "10.20.30"
pptpd_client_dir: "/etc/ppp"

# CoovaChilli
enable_coovachilli_support: no
coovachilli_service_name: chilli
coovachilli_conf_dir: "/etc/chilli"
coovachilli_default_conf: "/etc/default/chilli"
coovachilii_lan_if: "eth2"
coovachilii_wan_if: "eth1"
coovachilii_server_ip: "192.168.2.1"
coovachilii_network_addr: "192.168.2.0"
coovachilii_network_subnet: "255.255.255.0"
coovachilii_uam_port: 3990
coovachilii_uam_secret: "greatsecret"
coovachilii_radius_server1: "localhost"
coovachilii_radius_server2: "localhost"
coovachilii_dns_server1: "208.67.222.222"
coovachilii_dns_server2: "208.67.220.220"
coovachilii_user: "chilli"
coovachilii_group: "chilli"
coovachilli_coaport: 3799

# MAO Repository
mao_apt_ppa_repo: "ppa:muffycompoqm/rd-installer-fr3"
mao_apt_repo_key: "http://apt.maomuffy.com/ubuntu/apt_keys/rd_installer_mao.asc"

# NodeJS Repository
node_apt_repo_key: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

