---
# Apache (RHEL/CentOS 6+)
apache_pkg_name: httpd

# RadiusDesk Packages (RHEL/CentOS 6+)
rd_pkgs:
 - mysql-server
 - mysql
 - subversion
 - git
 - cronie
 - mailx
 - python
 - MySQL-python
 - perl
 - unixODBC
 - postgresql
 - openldap
 - libtool-ltdl
 - gcc-c++
 - gcc
 - make
 - unzip
 - tar

# RadiusDesk PHP5 Packages (RHEL/CentOS 6+)
rd_php5_pkgs:
 - php-fpm
 - php-pear
 - php-gd
 - php-common
 - php-cli
 - php-mysql
 - php-xcache

# RadiusDesk PHP7 Packages (RHEL/CentOS 6+)
rd_php7_pkgs: null

# Nginx (RHEL/CentOS 6+)
nginx_pkg_name: nginx
nginx_service_name: nginx
nginx_webroot: "/usr/share/nginx/html"
nginx_config: "/etc/nginx/nginx.conf"
nginx_default_config: "/etc/nginx/conf.d/default.conf"
nginx_worker_processes: 4
nginx_user: nginx

# PHP-FPM (RHEL/CentOS 6+)
php_fpm_service_name: php-fpm
php_fpm_config: "/etc/php-fpm.d/www.conf"
php_fpm_socket: "/var/run/php-fpm.sock"
php_session_save_path: "/var/lib/php/session"
php_config_file: "/etc/php.ini"
php_timezone: "Africa/Lagos"

# PHP7-FPM (RHEL/CentOS 6+)
php7_fpm_service_name: null
php7_fpm_config: null
php7_fpm_socket: null
php7_config_file: null

# Web server (RHEL/CentOS 6+)
web_user: apache
web_group: apache

# Temporary Download Directory
temp_src_dir: "/tmp/rd_sources"

# Radiusdesk Sources Repo Paths (RHEL/CentOS 6+)
cakephp_git_repo: "https://github.com/cakephp/cakephp.git"
rd_svn_repo: "https://svn.code.sf.net/p/radiusdesk/code/trunk/rd"
rd_cake_svn_repo: "https://svn.code.sf.net/p/radiusdesk/code/trunk/rd_cake"
rd_login_svn_repo: "https://svn.code.sf.net/p/radiusdesk/code/trunk/rd_login"
extjs_src_url: "https://sourceforge.net/p/radiusdesk/code/HEAD/tree/extjs/ext-6-sencha_cmd.tar.gz?format=raw"
extjs_src_md5_sum: "e829741694be90a27d7f0c6a24dbfc8b"
rd_svn_revision: 1951

# Freeradius Packages (RHEL/CentOS 6+)
freeradius_pkgs:
 - freeradius-3.0.11*
 - freeradius-mysql-3.0.11*
 - freeradius-perl-3.0.11*
 - freeradius-python-3.0.11*
 - freeradius-ldap-3.0.11*
 - freeradius-utils-3.0.11*
 - freeradius-krb5-3.0.11*

# Freeradius (RHEL/CentOS 6+)
freeradius_conf_dir: "/etc/raddb"
freeradius_prefix_path: "/usr"
freeradius_sbin_dir: "/usr/sbin"
freeradius_bin_dir: "/usr/bin"
freeradius_shared_dir: "/usr/share/freeradius"
freeradius_service_name: radiusd
freeradius_user: radiusd
freeradius_group: radiusd
freeradius_log_dir: "/var/log/radius"
freeradius_radclient: "/usr/bin/radclient"
freeradius_secret: "testing123"
allow_vulnerable_openssl: yes

# Radiusdesk Database (RHEL/CentOS 6+)
rd_db_user: rd
rd_db_password: rd
rd_db_name: rd

# MySQL (RHEL/CentOS 6+)
mysql_old_root_password: ""
mysql_root_password: root
mysql_service_name: mysqld
mysql_db_hosts:
 - 127.0.0.1
 - localhost
mysql_my_cnf: "~/.my.cnf"

# Nodejs Packages (RHEL/CentOS 6+)
nodejs_pkgs:
 - nodejs
 - npm

# Nodejs Modules (RHEL/CentOS 6+)
nodejs_npm_modules:
 - tail
 - connect
 - mysql
 - forever

nodejs_socketio_service_name: "nodejs-socket-io"
nodejs_socketio_app_path: "/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript/"

# PPTPD
enable_pptpd_support: yes
pptpd_service_name: pptpd
pptpd_local_ip_network: "10.20.30"
pptpd_client_dir: "/etc/ppp"

# CoovaChilli
enable_coovachilli_support: no
coovachilli_service_name: chilli
coovachilli_conf_dir: "/etc/chilli"
coovachilli_default_conf: ""
coovachilii_lan_if: "eth2"
coovachilii_wan_if: "eth1"
coovachilii_server_ip: "192.168.2.1"
coovachilii_network_addr: "192.168.2.0"
coovachilii_network_subnet: "255.255.255.0"
coovachilii_uam_port: 3990
coovachilii_uam_secret: "greatsecret"
coovachilii_radius_server1: "localhost"
coovachilii_radius_server2: "localhost"
coovachilii_dns_server1: "208.67.222.222"
coovachilii_dns_server2: "208.67.220.220"
coovachilii_user: "chilli"
coovachilii_group: "chilli"
coovachilli_coaport: 3799

